import pic from "./img/light3.jfif"
import lg from "./img/babe1.jpg"
import lg1 from "./img/babe.jpg"
import lg2 from "./img/babe2.JPG"

const products = [
    {
        _id: 1,
        name: "Bad Ringlights",
        image: pic,
        description: "The quick brown fox jumps over the lazy dog",
        brand: "Apple",
        category: "Electronics",
        price: 89.99,
        countInStock: 3,
        rating: 4.5,
        numReviews: 4,
    },
    {
        _id: 2,
        name: "Bad Ringlights",
        image: pic,
        description: "The quick brown fox jumps over the lazy dog",
        brand: "Apple",
        category: "Electronics",
        price: 89.99,
        countInStock: 3,
        rating: 4.5,
        numReviews: 4,
    },
    {
        _id: 3,
        name: "Fresh Ringlight",
        image: pic,
        images: [pic, lg, lg1, lg2],
        colors: ["red", "black", "crimson", "teal"],
        description: "The quick brown fox jumps over the lazy dog",
        brand: "Apple",
        category: "Electronics",
        price: 89.99,
        countInStock: 3,
        rating: 4.5,
        numReviews: 4,
    },
    {
        _id: 4,
        name: "Perfect Ringlights",
        image: pic,
        description: "The quick brown fox jumps over the lazy dog",
        brand: "Apple",
        category: "Electronics",
        price: 89.99,
        countInStock: 3,
        rating: 4.5,
        numReviews: 4,
    },
    {
        _id: 5,
        name: "Perfect Ringlights",
        image: pic,
        description: "The quick brown fox jumps over the lazy dog",
        brand: "Apple",
        category: "Electronics",
        price: 89.99,
        countInStock: 3,
        rating: 4.5,
        numReviews: 4,
    },
    {
        _id: 6,
        name: "Perfect Ringlights",
        image: pic,
        description: "The quick brown fox jumps over the lazy dog",
        brand: "Apple",
        category: "Electronics",
        price: 89.99,
        countInStock: 3,
        rating: 4.5,
        numReviews: 4,
    },
]

export default products