import pic from "./img/light3.jfif"

const products = [
    {
        _id: 1,
        name: "Airpods Wireless Bluetooth Headphones",
        image: pic,
        description: "The quick brown fox jumps over the lazy dog",
        brand: "Apple",
        category: "Electronics",
        price: 89.99,
        countInStock: 3,
        rating: 4.5,
        numReviews: 4,
    },
    {
        _id: 2,
        name: "Airpods Wireless Bluetooth Headphones",
        image: pic,
        description: "The quick brown fox jumps over the lazy dog",
        brand: "Apple",
        category: "Electronics",
        price: 89.99,
        countInStock: 3,
        rating: 4.5,
        numReviews: 4,
    },
    {
        _id: 3,
        name: "Airpods Wireless Bluetooth Headphones",
        image: pic,
        description: "The quick brown fox jumps over the lazy dog",
        brand: "Apple",
        category: "Electronics",
        price: 89.99,
        countInStock: 3,
        rating: 4.5,
        numReviews: 4,
    },
    {
        _id: 4,
        name: "Airpods Wireless Bluetooth Headphones",
        image: pic,
        description: "The quick brown fox jumps over the lazy dog",
        brand: "Apple",
        category: "Electronics",
        price: 89.99,
        countInStock: 3,
        rating: 4.5,
        numReviews: 4,
    },
    {
        _id: 5,
        name: "Airpods Wireless Bluetooth Headphones",
        image: pic,
        description: "The quick brown fox jumps over the lazy dog",
        brand: "Apple",
        category: "Electronics",
        price: 89.99,
        countInStock: 3,
        rating: 4.5,
        numReviews: 4,
    },
    {
        _id: 6,
        name: "Airpods Wireless Bluetooth Headphones",
        image: pic,
        description: "The quick brown fox jumps over the lazy dog",
        brand: "Apple",
        category: "Electronics",
        price: 89.99,
        countInStock: 3,
        rating: 4.5,
        numReviews: 4,
    },
]

export default products